services:
  springboot-ci-cd:
    image: springboot-ci-cd:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spring-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}?currentSchema=spring_app
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    deploy:
      replicas: 1

networks:
  spring-network:
    name: spring-network
    driver: bridge

volumes:
  postgres:
    driver: local
